#!/usr/bin/env python3
"""Copy artifact-comments into this kit, so the kit ships one tested version of it.

    python scripts/vendor_comments.py                      # from ../artifact-comments
    python scripts/vendor_comments.py --source ~/src/artifact-comments
    python scripts/vendor_comments.py --check              # exit 1 if the copy is out of date

artifact-comments is its own project (https://github.com/BrianArfi/artifact-comments).
The kit carries a copy under artifact-comments/ so that one clone has everything.
Never edit the copy: change artifact-comments upstream, then run this script.
The version copied is recorded in artifact-comments/VENDORED.json.

Standard library only.
"""
import argparse
import filecmp
import hashlib
import json
import os
import re
import shutil
import sys
from datetime import datetime, timezone

KIT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEST = os.path.join(KIT, 'artifact-comments')
DEFAULT_SOURCE = os.path.join(os.path.dirname(KIT), 'artifact-comments')

# What the kit needs from artifact-comments. SKILL.md is left out on purpose:
# the kit has its own, and a second one would be loaded as a separate skill.
ITEMS = ['client', 'functions', 'server', 'scripts', 'examples', 'docs', 'tests',
         'README.md', 'CHANGELOG.md', 'LICENSE', 'NOTICE']
SKIP = {'__pycache__', 'node_modules', '.wrangler', 'state', '.DS_Store'}
SKIP_SUFFIX = ('.pyc', '.pyo', '.db', '.db-wal', '.db-shm', '.log')
VERSION_RE = re.compile(r'''\bVERSION\s*=\s*['"](\d+\.\d+\.\d+)['"]''')

try:
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
except Exception:
    pass


def skipped(name):
    return name in SKIP or name.endswith(SKIP_SUFFIX)


def files_of(root):
    """Relative paths of every file the kit takes from root."""
    out = []
    for item in ITEMS:
        path = os.path.join(root, item)
        if os.path.isfile(path):
            out.append(item)
            continue
        for dirpath, dirnames, filenames in os.walk(path):
            dirnames[:] = sorted(d for d in dirnames if not skipped(d))
            for f in sorted(filenames):
                if not skipped(f):
                    out.append(os.path.relpath(os.path.join(dirpath, f), root).replace(os.sep, '/'))
    return out


def source_version(src):
    client = os.path.join(src, 'client', 'artifact-comments.js')
    with open(client, encoding='utf-8') as fh:
        m = VERSION_RE.search(fh.read())
    if not m:
        sys.exit(f'No VERSION constant in {client}')
    return m.group(1)


def digest(root, rels):
    h = hashlib.sha256()
    for rel in rels:
        h.update(rel.encode())
        with open(os.path.join(root, rel), 'rb') as fh:
            h.update(fh.read())
    return h.hexdigest()[:16]


def check(src):
    want = files_of(src)
    have = files_of(DEST) if os.path.isdir(DEST) else []
    missing = sorted(set(want) - set(have))
    extra = sorted(set(have) - set(want))
    changed = [r for r in want if r in have and not filecmp.cmp(os.path.join(src, r), os.path.join(DEST, r), shallow=False)]
    for label, rows in (('missing', missing), ('extra', extra), ('changed', changed)):
        for r in rows:
            print(f'  {label}: {r}')
    if missing or extra or changed:
        print('artifact-comments copy is OUT OF DATE. Run: python scripts/vendor_comments.py')
        return 1
    print(f'artifact-comments copy matches {src} (v{source_version(src)})')
    return 0


def vendor(src):
    rels = files_of(src)
    if not rels:
        sys.exit(f'Nothing to copy from {src}')
    if os.path.isdir(DEST):
        shutil.rmtree(DEST)
    for rel in rels:
        out = os.path.join(DEST, rel)
        os.makedirs(os.path.dirname(out), exist_ok=True)
        shutil.copyfile(os.path.join(src, rel), out)
    version = source_version(src)
    note = {
        'package': 'artifact-comments',
        'version': version,
        'upstream': 'https://github.com/BrianArfi/artifact-comments',
        'vendored_at': datetime.now(timezone.utc).strftime('%Y-%m-%d'),
        'files': len(rels),
        'sha256_16': digest(DEST, rels),
        'note': 'Generated by scripts/vendor_comments.py. Do not edit files in this folder; '
                'change artifact-comments upstream and vendor again.',
    }
    with open(os.path.join(DEST, 'VENDORED.json'), 'w', encoding='utf-8', newline='\n') as fh:
        json.dump(note, fh, indent=2)
        fh.write('\n')
    print(f'vendored artifact-comments v{version}: {len(rels)} files into {DEST}')
    return 0


def main():
    ap = argparse.ArgumentParser(description='Copy artifact-comments into the kit.')
    ap.add_argument('--source', default=DEFAULT_SOURCE, help='artifact-comments folder or clone')
    ap.add_argument('--check', action='store_true', help='compare only; exit 1 when out of date')
    a = ap.parse_args()
    src = os.path.abspath(os.path.expanduser(a.source))
    if not os.path.isfile(os.path.join(src, 'client', 'artifact-comments.js')):
        sys.exit(f'{src} is not an artifact-comments folder (no client/artifact-comments.js).\n'
                 'Clone https://github.com/BrianArfi/artifact-comments and pass --source.')
    return check(src) if a.check else vendor(src)


if __name__ == '__main__':
    sys.exit(main())
